import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv(r"C:\Users\HP\Documents\Student_performace\Gpa.csv")
df=pd.DataFrame(data)
print(df.head())
avg= df['GPA'].mean()
print("Average gpa=",avg)
df=df.drop("Student_ID",axis=1)
corr=df.corr()
print(corr["GPA"].drop("GPA"))
sns.heatmap(corr,annot=True,cmap="coolwarm", fmt=".2f")
plt.title("correlation heatmap")
plt.show()
#study hours vs gpa
plt.scatter(df["Study_Hours"], df["GPA"],color="red")
plt.xlabel("Study_Hours")
plt.ylabel("GPA")
plt.title("Study hours vs GPA")
plt.grid()
plt.show()
#sleep hours vs gpa
plt.scatter(df["Sleep_Hours"], df["GPA"])
plt.xlabel("Sleep_Hours")
plt.ylabel("GPA")
plt.title("Sleep hours vs GPA")
plt.grid()
plt.show()
# stress level vs gpa
plt.scatter(df["Stress_level"], df["GPA"],color="green")
plt.xlabel("Stress Level")
plt.ylabel("GPA")
plt.title("Stress vs GPA")
plt.grid()
plt.show()
sns.regplot(x="Study_Hours", y="GPA", data=df, scatter_kws={"color":"blue"}, line_kws={"color":"black"})
plt.title("Study Hours vs GPA with Trend Line")
plt.show()
print("\nINSIGHTS:")
print("1. Study hours positively impact GPA")
print("2. Higher stress levels reduce GPA")
print("3. Proper sleep improves performance")
